name: Python package

on:
  push:
    branches: [ "master" ]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up React app
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install React dependencies
      run: |
        cd /home/chloe/blockchain-w-gh-actions/blockchain-app/Blockchain/Blockchain/frontend && npm install
    - name: Build React application
      run: |      
        cd /home/chloe/blockchain-w-gh-actions/blockchain-app/Blockchain/Blockchain/frontend && npm run build
        
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Flask dependencies
      run: cd /home/chloe/blockchain-w-gh-actions/blockchain-app/Blockchain/Blockchain/backend && pip install -r requirements.txt
        
  run-app:
    name: Deploy app
    runs-on: self-hosted
    needs: [build-frontend, build-backend]
    steps:
    - uses: actions/checkout@v3
    - name: Reload PM2 
      run: pm2 restart Blocky
